# Generated by Django 5.2.7 on 2025-11-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_contactpage_homepage_aboutpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
