# Generated by Django 5.2.7 on 2025-11-26 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Summer Promo', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Discount amount (e.g. 50.00)', max_digits=5)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('expiration', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='firstapp.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
