# Generated by Django 5.2.7 on 2025-11-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_coupon_claimed_by_alter_coupon_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(help_text='e.g. Summer Promo', max_length=50),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Discount amount', max_digits=5),
        ),
    ]
