# Generated by Django 5.2.7 on 2025-11-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_alter_coupon_name_alter_coupon_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='active',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='is_used',
        ),
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
