# Generated by Django 5.2.7 on 2025-11-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_remove_coupon_active_remove_coupon_is_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='claimed_by',
        ),
    ]
