# Generated by Django 5.2.7 on 2025-11-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_coupon_claimed_by_alter_coupon_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='claimed_by',
        ),
    ]
