# Generated by Django 5.2.7 on 2025-11-29 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_coupon_claimed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitem',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_items', to='firstapp.coupon'),
        ),
    ]
