# Generated by Django 5.2.7 on 2025-11-29 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_receiptitem_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='firstapp.coupon'),
        ),
    ]
