# Generated by Django 5.2.7 on 2025-11-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_receipt_status_receipt_voided_at_receipt_voided_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='void_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
