# Generated by Django 5.2.7 on 2025-12-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
