# Generated by Django 5.2.7 on 2025-12-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('chicken', 'Chicken'), ('beef', 'Beef'), ('fish', 'Fish'), ('vegetables', 'Vegetables'), ('combo_meal', 'Combo Meal'), ('value_meal', 'Value Meal'), ('add_on', 'Add-on'), ('others', 'Others')], max_length=20),
        ),
    ]
