# Generated by Django 5.2.7 on 2025-12-06 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0022_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='claimed_by',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='product',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='rate',
        ),
        migrations.AddField(
            model_name='coupon',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Total times this code can be used', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Expired', 'Expired')], default='Active', max_length=20),
        ),
        migrations.CreateModel(
            name='CouponCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name like 'Summer Sale 20%'", max_length=100)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('free_item', 'Free Item (Buy X Get Y)')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Percentage or Fixed Amount', max_digits=10)),
                ('min_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_quantity', models.PositiveIntegerField(default=0, help_text='Min total items in cart or min items of specific category')),
                ('target_category', models.CharField(blank=True, help_text='If set, applies only to this category', max_length=50, null=True)),
                ('is_new_user_only', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('free_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteria_free_product', to='firstapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='firstapp.couponcriteria'),
        ),
    ]
