# Generated by Django 5.2.7 on 2025-12-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_remove_product_stock_quantity_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Claimed', 'Claimed'), ('Redeemed', 'Redeemed'), ('Expired', 'Expired')], default='Active', max_length=20),
        ),
    ]
