# Generated by Django 5.2.7 on 2025-12-08 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0025_alter_coupon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcriteria',
            name='target_product',
            field=models.ForeignKey(blank=True, help_text='If set, the discount applies ONLY to this product, not the total bill.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_coupons', to='firstapp.product'),
        ),
        migrations.DeleteModel(
            name='Costing',
        ),
    ]
