# Generated by Django 5.2.7 on 2025-12-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0028_coupon_claimed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=False),
        ),
    ]
