# Generated by Django 5.2.7 on 2025-12-09 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0029_product_stock_quantity_product_track_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='claimed_by',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Total times this code can be claimed', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='claimed_by',
            field=models.ManyToManyField(blank=True, related_name='claimed_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
