# Generated by Django 5.2.8 on 2026-01-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0031_receipt_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='brand_name',
            field=models.CharField(default='Kuya Vince Karinderya', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cuisine_type',
            field=models.CharField(default='Pinoy bayan cuisine', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_end',
            field=models.TextField(default='— flavorful, hearty, and made just like how'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_final',
            field=models.TextField(default='used to cook.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_middle',
            field=models.TextField(default=', we take pride in serving the best'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_start',
            field=models.CharField(default='At', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_line1_end',
            field=models.CharField(default='AND TRADITION', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_line1_highlight',
            field=models.CharField(default='LOVE', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_line1_start',
            field=models.CharField(default='SAVOR THE TASTE OF', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_line2_highlight',
            field=models.CharField(default='BITE', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_line2_start',
            field=models.CharField(default='IN EVERY', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='lola_text',
            field=models.CharField(default='lola', max_length=50),
        ),
    ]
