# Generated by Django 5.2.8 on 2026-01-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0032_homepage_brand_name_homepage_cuisine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/'),
        ),
    ]
