# Generated by Django 6.0.1 on 2026-02-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0032_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='coupon',
        ),
        migrations.AddField(
            model_name='receipt',
            name='coupons',
            field=models.ManyToManyField(blank=True, related_name='receipts', to='firstapp.coupon'),
        ),
    ]
