# Generated by Django 5.2.8 on 2026-01-18 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0033_alter_homepage_banner_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page Content', 'verbose_name_plural': 'Home Page Content'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Homepage hero banner image (optional)', null=True, upload_to='homepage/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='brand_name',
            field=models.CharField(default='Kuya Vince Karinderya', help_text='Brand name (shown in red)', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cuisine_type',
            field=models.CharField(default='Pinoy bayan cuisine', help_text='Type of cuisine (shown in red)', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description_end',
            field=models.TextField(default='— flavorful, hearty, and made just like how', help_text='Description before lola text'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description_final',
            field=models.TextField(default='used to cook.', help_text='Final part of description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description_middle',
            field=models.TextField(default=', we take pride in serving the best', help_text='Middle section of description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description_start',
            field=models.CharField(default='At', help_text='Opening word of description', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='dishes',
            field=models.CharField(default='POPULAR DISHES', help_text='Title for popular dishes section', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_line1_end',
            field=models.CharField(default='AND TRADITION', help_text='End part of headline line 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_line1_highlight',
            field=models.CharField(default='LOVE', help_text='Highlighted (red) word in line 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_line1_start',
            field=models.CharField(default='SAVOR THE TASTE OF', help_text='First part of headline line 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_line2_highlight',
            field=models.CharField(default='BITE', help_text='Highlighted (red) word in line 2', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_line2_start',
            field=models.CharField(default='IN EVERY', help_text='First part of headline line 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='lola_text',
            field=models.CharField(default='lola', help_text="Word 'lola' (shown in bold)", max_length=50),
        ),
    ]
