# Generated by Django 5.2.8 on 2026-01-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0034_alter_homepage_options_homepage_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title/description of this image', max_length=100)),
                ('image', models.ImageField(help_text='Upload image', upload_to='homepage_images/')),
                ('image_type', models.CharField(choices=[('carousel', 'Carousel Image'), ('feature', 'Feature Image'), ('footer', 'Footer Image'), ('other', 'Other')], default='other', help_text='Where this image will be used', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order (for carousel/galleries)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this image on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Image',
                'verbose_name_plural': 'Homepage Images',
                'ordering': ['image_type', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PopularDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the popular dish', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Image of the dish (optional)', null=True, upload_to='popular_dishes/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this dish on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Popular Dish',
                'verbose_name_plural': 'Popular Dishes',
                'ordering': ['order', 'name'],
            },
        ),
    ]
