# Generated by Django 5.2.8 on 2026-01-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0035_homepageimage_populardish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Service title (e.g., DAILY)', max_length=100)),
                ('subtitle', models.CharField(help_text='Service subtitle (e.g., SPECIALS)', max_length=100)),
                ('icon_name', models.CharField(choices=[('Clock', 'Clock'), ('Heart', 'Heart'), ('Star', 'Star'), ('Utensils', 'Utensils'), ('Users', 'Users'), ('PartyPopper', 'PartyPopper'), ('Quote', 'Quote')], default='Clock', help_text='Icon to display', max_length=50)),
                ('description', models.TextField(help_text='Service description')),
                ('features', models.JSONField(default=list, help_text="List of features as JSON array: ['Feature 1', 'Feature 2', ...]")),
                ('featured', models.BooleanField(default=False, help_text='Mark as featured (red background)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this service on the page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_prefix', models.CharField(default='OUR', help_text='Title prefix text', max_length=50)),
                ('title_highlight', models.CharField(default='SERVICES', help_text='Title highlight text (shown in red)', max_length=50)),
                ('description', models.TextField(default='At Kuya Vince Karinderya, we extend our warm Filipino hospitality through a wide variety of services designed to bring authentic Pinoy Bayan Cuisine to every occasion.', help_text='Services page description')),
                ('highlight_title', models.CharField(default='AUTHENTIC FILIPINO DINING EXPERIENCE', help_text='Highlight box title', max_length=200)),
                ('highlight_description', models.TextField(default='Experience the warmth of Filipino hospitality and the rich flavors of traditional Pinoy Bayan Cuisine.', help_text='Highlight box description')),
                ('highlight_stats', models.JSONField(default=list, help_text="Stats as JSON array: [{'label': 'Dishes', 'value': '50+'}, ...]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Services Page',
                'verbose_name_plural': 'Services Page',
            },
        ),
    ]
