# Generated by Django 5.2.8 on 2026-01-27 23:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0036_service_servicespage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Testimonial content')),
                ('author', models.CharField(help_text='Author name', max_length=100)),
                ('role', models.CharField(help_text='Author role/title', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About Page', 'verbose_name_plural': 'About Page'},
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='story',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='header_line1',
            field=models.CharField(default="WE'RE MORE", max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='header_line1_end',
            field=models.CharField(default='JUST A', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='header_line1_highlight',
            field=models.CharField(default='THAN', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='header_line1_highlight2',
            field=models.CharField(default='PLACE TO EAT,', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='header_line2',
            field=models.CharField(default="WE'RE A", max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='header_line2_end',
            field=models.CharField(default='OF', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='header_line2_highlight',
            field=models.CharField(default='TASTE', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='header_line2_highlight2',
            field=models.CharField(default='HOME.', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_footer',
            field=models.CharField(default='Masarap, malasakit, tulad ng pamilya!', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_p1',
            field=models.TextField(default='Inspired by the warmth of Filipino karinderyas...'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_p2',
            field=models.TextField(default='Our journey started with a simple mission...'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_title',
            field=models.CharField(default='Our Story', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values',
            field=models.JSONField(default=list, help_text="Array of values: [{'title': 'MALASAKIT', 'desc': '...', 'iconName': 'Heart'}, ...]"),
        ),
    ]
