# Generated by Django 6.0.1 on 2026-02-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0036_alter_otp_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_prefix', models.CharField(default='OUR', max_length=50)),
                ('title_highlight', models.CharField(default='SERVICES', max_length=50)),
                ('description', models.TextField(default='At Kuya Vince Karinderya, we extend our warm Filipino hospitality...')),
                ('s1_title', models.CharField(default='DAILY', max_length=50)),
                ('s1_subtitle', models.CharField(default='SPECIALS', max_length=50)),
                ('s1_desc', models.TextField(default='Freshly cooked meals prepared daily.')),
                ('s2_title', models.CharField(default='AFFORDABLE', max_length=50)),
                ('s2_subtitle', models.CharField(default='MEAL PLANS', max_length=50)),
                ('s2_desc', models.TextField(default='Budget-friendly meal packages.')),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='story',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='dishes',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='footer_text',
            field=models.CharField(default='Masarap, malasakit, tulad ng pamilya!', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='line1',
            field=models.CharField(default="WE'RE MORE", max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='line1_end',
            field=models.CharField(default='JUST A', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='line1_highlight',
            field=models.CharField(default='THAN', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='line1_highlight2',
            field=models.CharField(default='PLACE TO EAT,', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='line2',
            field=models.CharField(default="WE'RE A", max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='line2_end',
            field=models.CharField(default='OF', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='line2_highlight',
            field=models.CharField(default='TASTE', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='line2_highlight2',
            field=models.CharField(default='HOME.', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_p1',
            field=models.TextField(default='Inspired by the warmth...'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_p2',
            field=models.TextField(default='Our journey started...'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_title',
            field=models.CharField(default='Our Story', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='fb_label',
            field=models.CharField(default='Kuya Vince Karinderya', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='header_highlight',
            field=models.CharField(default='CONTACT', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='header_suffix',
            field=models.CharField(default='US', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subtitle',
            field=models.CharField(default='We’d love to hear from you!', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='brand_name',
            field=models.CharField(default='Kuya Vince Karinderya', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cuisine_type',
            field=models.CharField(default='Pinoy bayan cuisine', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_end',
            field=models.TextField(default='— flavorful, hearty, and made just like how'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_final',
            field=models.CharField(default='used to cook.', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_middle',
            field=models.CharField(default=', we take pride in serving the best', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_start',
            field=models.CharField(default='At', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='line1_end',
            field=models.CharField(default='AND TRADITION', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='line1_highlight',
            field=models.CharField(default='LOVE', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='line1_start',
            field=models.CharField(default='SAVOR THE TASTE OF', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='line2_highlight',
            field=models.CharField(default='BITE', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='line2_start',
            field=models.CharField(default='IN EVERY', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='lola_text',
            field=models.CharField(default='lola', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='fb_page',
            field=models.CharField(max_length=200),
        ),
    ]
