# Generated by Django 5.2.8 on 2026-01-27 23:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0037_testimonial_alter_aboutpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact Page', 'verbose_name_plural': 'Contact Page'},
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='fb_page',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='facebook_label',
            field=models.CharField(default='Kuya Vince Karinderya', help_text='Facebook page display name', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='facebook_link',
            field=models.URLField(default='https://facebook.com', help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='header_highlight',
            field=models.CharField(default='CONTACT', help_text='Highlighted text (shown in red)', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='header_subtitle',
            field=models.TextField(default="We'd love to hear from you!", help_text='Subtitle under the header'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='header_suffix',
            field=models.CharField(default='US', help_text='Suffix text after highlight', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone',
            field=models.CharField(default='0912 345 6789', help_text='Phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='address',
            field=models.TextField(default='Cagayan de Oro City, Misamis Oriental', help_text='Physical address'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(default='kuyavince@example.com', help_text='Email address', max_length=254),
        ),
    ]
