# Generated by Django 5.2.8 on 2026-01-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0038_alter_contactpage_options_remove_contactpage_fb_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Label (e.g., Phone, Email)', max_length=50)),
                ('value', models.CharField(help_text='Contact value (e.g., phone number, email address)', max_length=200)),
                ('link', models.CharField(help_text='Link (e.g., tel:, mailto:, https://)', max_length=500)),
                ('icon_name', models.CharField(choices=[('Phone', 'Phone'), ('Mail', 'Email'), ('MapPin', 'Map Pin'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Globe', 'Website')], default='Phone', help_text='Icon to display', max_length=50)),
                ('color', models.CharField(choices=[('purple', 'Purple'), ('red', 'Red'), ('pink', 'Pink'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('indigo', 'Indigo')], default='purple', help_text='Color theme', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this contact info')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='facebook_label',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='phone',
        ),
    ]
