# Generated by Django 6.0.1 on 2026-02-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0038_category_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='void_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
