# Generated by Django 6.0.1 on 2026-03-06 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0041_userprofile_deactivated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcriteria',
            name='is_new_user_only',
        ),
        migrations.RemoveField(
            model_name='couponcriteria',
            name='min_quantity',
        ),
        migrations.RemoveField(
            model_name='couponcriteria',
            name='valid_from',
        ),
    ]
