# Generated by Django 6.0.1 on 2026-03-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0042_remove_couponcriteria_is_new_user_only_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySalesReport',
        ),
    ]
