# Generated by Django 6.0.1 on 2026-03-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0043_delete_dailysalesreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='max_coupons_per_order',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
