# Generated by Django 6.0.1 on 2026-03-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0048_aboutpage_open_hours_aboutpage_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='claim_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Total times this code can be CLAIMED by users in the app', null=True),
        ),
    ]
