# Generated by Django 6.0.1 on 2026-03-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0049_coupon_claim_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='times_claimed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
