# Generated by Django 6.0.1 on 2026-03-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0055_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='checkout_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
