# Generated by Django 6.0.1 on 2026-04-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0056_alter_paymenttransaction_checkout_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='pos_cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
