# Generated by Django 6.0.1 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0061_coupon_archive_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='tin_number',
            field=models.CharField(default='123-456-789-000', max_length=15),
        ),
    ]
