# Generated by Django 6.0.1 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0062_storesettings_tin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='receipt_phone',
            field=models.CharField(default='+63 966 443 1581', max_length=25),
        ),
    ]
