# Generated by Django 6.0.1 on 2026-04-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0068_drawerbalancelog_and_pos_initial_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_completed_orders',
            field=models.PositiveIntegerField(default=0, help_text='Required completed POS orders when audience is frequent customers.'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='target_audience',
            field=models.CharField(choices=[('all_users', 'All Users'), ('frequent_customers', 'Frequent Customers')], default='all_users', help_text='Controls which users can see and claim this coupon.', max_length=32),
        ),
        migrations.CreateModel(
            name='CouponClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='firstapp.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('coupon', 'user')},
            },
        ),
    ]
